### ISSUE TITLE
Can no longer checkout after first attempt to do full checkout

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor-storefront#105]
1. Attempted a full checkout (as `admin@example.com`), which may have failed or not;
2. Attempted a second time to make a checkout;
3. Error.

```
TypeError: "d is null"

	gi
react-dom.production.min.js:181:139
Si/n.callback
react-dom.production.min.js:189:469
co
react-dom.production.min.js:128:451
lo
react-dom.production.min.js:128:248
ka
react-dom.production.min.js:228:201
Ia
react-dom.production.min.js:218:80
Aa
react-dom.production.min.js:217:172
Ta
react-dom.production.min.js:214:214
Gi
react-dom.production.min.js:212:36
enqueueSetState
react-dom.production.min.js:133:222
_.prototype.setState
react.production.min.js:13:210
E/this.getCheckout/<
index.tsx:45
a
index.tsx:4:41

```

## Request

```
Host: demo.getsaleor.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://pwa.getsaleor.com/cart/76676168-68d3-4d94-9253-625b9c72aacf/
content-type: application/json
origin: https://pwa.getsaleor.com
Content-Length: 2162
Connection: keep-alive
TE: Trailers

{
    "operationName": "getCheckout",
    "variables": {
        "token": "76676168-68d3-4d94-9253-625b9c72aacf"
    },
    "query": "fragment Checkout on Checkout {\n  token\n  id\n  totalPrice {\n    net {\n      amount\n      __typename\n    }\n    gross {\n      amount\n      localized\n      __typename\n    }\n    currency\n    __typename\n  }\n  subtotalPrice {\n    net {\n      amount\n      __typename\n    }\n    gross {\n      amount\n      localized\n      __typename\n    }\n    currency\n    __typename\n  }\n  billingAddress {\n    firstName\n    lastName\n    companyName\n    streetAddress1\n    streetAddress2\n    city\n    postalCode\n    country {\n      code\n      country\n      __typename\n    }\n    countryArea\n    phone\n    __typename\n  }\n  shippingAddress {\n    firstName\n    lastName\n    companyName\n    streetAddress1\n    streetAddress2\n    city\n    postalCode\n    country {\n      code\n      country\n      __typename\n    }\n    countryArea\n    phone\n    __typename\n  }\n  email\n  availableShippingMethods {\n    id\n    name\n    price {\n      currency\n      amount\n      localized\n      __typename\n    }\n    __typename\n  }\n  shippingMethod {\n    id\n    name\n    price {\n      currency\n      amount\n      localized\n      __typename\n    }\n    __typename\n  }\n  shippingPrice {\n    net {\n      amount\n      __typename\n    }\n    gross {\n      amount\n      localized\n      __typename\n    }\n    currency\n    __typename\n  }\n  lines {\n    id\n    quantity\n    totalPrice {\n      net {\n        amount\n        __typename\n      }\n      gross {\n        amount\n        localized\n        __typename\n      }\n      currency\n      __typename\n    }\n    variant {\n      id\n      name\n      price {\n        amount\n        currency\n        localized\n        __typename\n      }\n      product {\n        id\n        name\n        thumbnailUrl\n        thumbnailUrl2x: thumbnailUrl(size: 510)\n        __typename\n      }\n      __typename\n    }\n    quantity\n    __typename\n  }\n  __typename\n}\n\nquery getCheckout($token: UUID!) {\n  checkout(token: $token) {\n    ...Checkout\n    __typename\n  }\n}\n"
}
```

## Response
```
HTTP/2.0 200 OK
content-type: application/json
content-length: 3068
date: Wed, 31 Oct 2018 20:11:57 GMT
server: nginx/1.12.1
vary: Cookie, Accept-Language
access-control-allow-origin: *
access-control-allow-methods: POST, OPTIONS
access-control-allow-headers: Origin, Content-Type, Accept, Authorization
content-language: en
x-cache: Miss from cloudfront
via: 1.1 4d1cbe225c5d30aa78ec9a6fa1ba4211.cloudfront.net (CloudFront)
X-Firefox-Spdy: h2

{
    "data": {
        "checkout": {
            "token": "76676168-68d3-4d94-9253-625b9c72aacf",
            "id": "Q2hlY2tvdXQ6NzY2NzYxNjgtNjhkMy00ZDk0LTkyNTMtNjI1YjljNzJhYWNm",
            "totalPrice": {
                "net": {
                    "amount": 41.67,
                    "__typename": "Money"
                },
                "gross": {
                    "amount": 50.0,
                    "localized": "$50.00",
                    "__typename": "Money"
                },
                "currency": "USD",
                "__typename": "TaxedMoney"
            },
            "subtotalPrice": {
                "net": {
                    "amount": 41.67,
                    "__typename": "Money"
                },
                "gross": {
                    "amount": 50.0,
                    "localized": "$50.00",
                    "__typename": "Money"
                },
                "currency": "USD",
                "__typename": "TaxedMoney"
            },
            "billingAddress": {
                "firstName": "Hello",
                "lastName": "World",
                "companyName": "",
                "streetAddress1": "Avenue of the General Mc. Denille",
                "streetAddress2": "",
                "city": "Strasbourg",
                "postalCode": "67100",
                "country": {
                    "code": "FR",
                    "country": "France",
                    "__typename": "CountryDisplay"
                },
                "countryArea": "",
                "phone": "",
                "__typename": "Address"
            },
            "shippingAddress": {
                "firstName": "Hello",
                "lastName": "World",
                "companyName": "Hello World, INC",
                "streetAddress1": "Avenue of the General Mc. Denille",
                "streetAddress2": "",
                "city": "Strasbourg",
                "postalCode": "67100",
                "country": {
                    "code": "FR",
                    "country": "France",
                    "__typename": "CountryDisplay"
                },
                "countryArea": "",
                "phone": "",
                "__typename": "Address"
            },
            "email": "",
            "availableShippingMethods": [{
                "id": "U2hpcHBpbmdNZXRob2Q6MjU5",
                "name": "DB Schenker",
                "price": {
                    "currency": "USD",
                    "amount": 37.39,
                    "localized": "$37.39",
                    "__typename": "Money"
                },
                "__typename": "ShippingMethod"
            }],
            "shippingMethod": null,
            "shippingPrice": {
                "net": {
                    "amount": 0.0,
                    "__typename": "Money"
                },
                "gross": {
                    "amount": 0.0,
                    "localized": "$0.00",
                    "__typename": "Money"
                },
                "currency": "USD",
                "__typename": "TaxedMoney"
            },
            "lines": [{
                "id": "Q2hlY2tvdXRMaW5lOjMyNzA=",
                "quantity": 1,
                "totalPrice": {
                    "net": {
                        "amount": 25.0,
                        "__typename": "Money"
                    },
                    "gross": {
                        "amount": 30.0,
                        "localized": "$30.00",
                        "__typename": "Money"
                    },
                    "currency": "USD",
                    "__typename": "TaxedMoney"
                },
                "variant": {
                    "id": "UHJvZHVjdFZhcmlhbnQ6MTgx",
                    "name": "2.5l",
                    "price": {
                        "amount": 30.0,
                        "currency": "USD",
                        "localized": "$30.00",
                        "__typename": "Money"
                    },
                    "product": {
                        "id": "UHJvZHVjdDo2NA==",
                        "name": "Light Speed Yellow Paint",
                        "thumbnailUrl": "https://saleor-demo.s3.amazonaws.com/__sized__/products/saleordemoproduct_paints_04-thumbnail-255x255.png",
                        "thumbnailUrl2x": "https://saleor-demo.s3.amazonaws.com/__sized__/products/saleordemoproduct_paints_04-thumbnail-510x510.png",
                        "__typename": "Product"
                    },
                    "__typename": "ProductVariant"
                },
                "__typename": "CheckoutLine"
            }, {
                "id": "Q2hlY2tvdXRMaW5lOjMyNzQ=",
                "quantity": 1,
                "totalPrice": {
                    "net": {
                        "amount": 16.67,
                        "__typename": "Money"
                    },
                    "gross": {
                        "amount": 20.0,
                        "localized": "$20.00",
                        "__typename": "Money"
                    },
                    "currency": "USD",
                    "__typename": "TaxedMoney"
                },
                "variant": {
                    "id": "UHJvZHVjdFZhcmlhbnQ6MTk3",
                    "name": "45cm x 45cm",
                    "price": {
                        "amount": 20.0,
                        "currency": "USD",
                        "localized": "$20.00",
                        "__typename": "Money"
                    },
                    "product": {
                        "id": "UHJvZHVjdDo4NQ==",
                        "name": "Colored Parrot Cushion",
                        "thumbnailUrl": "https://saleor-demo.s3.amazonaws.com/__sized__/products/saleordemoproduct_cuschion01-thumbnail-255x255.png",
                        "thumbnailUrl2x": "https://saleor-demo.s3.amazonaws.com/__sized__/products/saleordemoproduct_cuschion01-thumbnail-510x510.png",
                        "__typename": "Product"
                    },
                    "__typename": "ProductVariant"
                },
                "__typename": "CheckoutLine"
            }],
            "__typename": "Checkout"
        }
    }
}
```

**Comment by maarcingebala** [comment]
After a short investigation, I think the problem might be caching the `checkout` object in Apollo. Not sure if this should work like this, but after I start checkout, go back to the shop and removed all products from the bag, the checkout remains in the cache, while I think it should be removed. To be discussed with the team.

**Comment by piotrgrundas** [comment]
@NyanKiyoshi Could You check please if that issue still occurs? I can't seem to reproduce it. If so could U provide exact steps to reproduce?

**Comment by NyanKiyoshi** [comment]
@piotrgrundas IIRC it has been fixed some time ago by @dominik-zeglen, but I'm not fully sure. I'm not able to complete test orders in `pwa.getsaleor.com`, the payment page doesn't give me any option to complete it.

I'm not sure that I could complete orders locally either, unless I'm missing something with the PWA's checkout process. Let me know, I can always give it a shot whenever I have a few minutes.

But, if you managed to complete two orders in a row, in the same session, then the issue should be fixed, and the issue can thus be closed.

**Comment by piotrgrundas** [comment]
Closing since I was able to place a couple orders in a row with no problem. I've even left the checkout, and returned to it after a while.

**Comment by 1H4CK3DP3NT4G0NWITHJS** [comment]
It looks like this problem (or similar one) still occurs in the latest Mozilla Firefox. In Chrome I can go through all payment process, but in Firefox SPA it reloads checkout page after choosing payment type and clicking "Continue to review your order" button.
