### ISSUE TITLE
Incorrect autofill tokens for addresses

### ISSUE THREAD

**Issue by michaljelonek** [mirumee/saleor-storefront#236]
### What I'm trying to achieve

Use the autofill functionality to fill in address details quickly.

### Steps to reproduce the problem
1. Go to any form that requires an address input, for example checkout.
2. Use the autofill functionality to fill in the address.

### What I expected to happen
City, county, phone number should be automatically filled, but they use the incorrect tokens for autofill to work. See here for correct ones: https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofill

### Screenshots
![image](https://user-images.githubusercontent.com/7791528/52203588-eb8fdc00-2871-11e9-8323-b8f6cfcbc4c9.png)

**System information**
Operating system: n/a
Browser: Chrome

**Comment by mateuszkula** [comment]
@maarcingebala This issue was already fixed, there was duplicated issue(#256 ) and it was mentioned in pull request(#264 ) instead of this one :)

**Comment by maarcingebala** [comment]
It still doesn't work for the country input, maybe it's because this one is a choice field and it requires some additional logic?

**Comment by mateuszkula** [comment]
You are right - I checked this particular field and it seems that [react-select](https://github.com/JedWatson/react-select) is being used for country selection. React-select does not support the autoFill option right now. There are at least 2 PRs with support for that functionality waiting to be merged but they are inactive for a few months.  Either we can wait for adding support to react-select, live without autofill for country or create custom dropdown/look for other libraries.

**Comment by mateuszkula** [comment]
This was fixed PR #312
