### ISSUE TITLE
Not able to view the shopping cart

### ISSUE THREAD

**Issue by codefl** [mirumee/saleor-storefront#739]
Hello,

I'm new to Saleor. I have given it a try locally using docker. After I added a product to the bag, I tried to view the shopping cart. But it shows empty page. The errors in the console shows error below "line.variant.product is undefined".

<img width="781" alt="Screen Shot 2020-05-26 at 12 06 38 PM" src="https://user-images.githubusercontent.com/8314758/82941714-b5390d00-9f4b-11ea-9a35-c2da16d12d0f.png">

Does anyone know what's wrong there? 

Thanks,
Frank

**Comment by Sanaj2060** [comment]
Check out the lastest commit on [saleor-storefront-master](https://github.com/mirumee/saleor-storefront), the issue has been resolved.

**Comment by codefl** [comment]
Thanks for the quick response. The error still persists. Below is what I have done:

Pulled the latest code and cleared the browser cache.

`
% git pull origin master
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 1), reused 2 (delta 1), pack-reused 0
Unpacking objects: 100% (3/3), done.
From https://github.com/mirumee/saleor-platform
 * branch            master     -> FETCH_HEAD
   119b3f1..4ee5fc2  master     -> origin/master
Fetching submodule saleor-storefront
Failed to add the RSA host key for IP address '140.82.113.3' to the list of known hosts (/Users/test/.ssh/known_hosts).
From github.com:mirumee/saleor-storefront
   be376bd1..df3b2802  2.10                   -> origin/2.10
 * [new branch]        cover-inputs-with-datacy -> origin/cover-inputs-with-datacy
   9ffc58e6..9c478313  master                 -> origin/master
 + 7367c7c9...7f53550b merge-with-demo        -> origin/merge-with-demo  (forced update)
 + da8d3076...2e57dd47 ref/separate-sdk       -> origin/ref/separate-sdk  (forced update)
 + 9fa444ac...704a1efc refactor/sdk-user-auth -> origin/refactor/sdk-user-auth  (forced update)
 * [new branch]        update-changelog       -> origin/update-changelog
 * [new tag]           2.10.2                 -> 2.10.2
Updating 119b3f1..4ee5fc2
Fast-forward
 saleor-storefront | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
`

**Add a product to the bag**

Observe: the "1" sign shows up in the bag. But see 4 graphql errors reported as:

`graphql.error.base.GraphQLError: Fields "quantityAvailable" conflict because they have differing arguments. Use different aliases on the fields to fetch both if this was intentional.`

![Screen Shot 2020-05-28 at 8 34 29 AM](https://user-images.githubusercontent.com/8314758/83162209-4b8d4000-a0be-11ea-887c-c2d1d7e3a49d.png)

**Click view the shopping cart**

Observe: blank screen with the same error reported in console as reported initially.

Thanks

**Comment by Sanaj2060** [comment]
I'm not sure if they update the saleon- platform, but my local deployment works fine. 
Make sure you log out recent login.

**Comment by codefl** [comment]
It works now. Thanks
